apiVersion: v1
## The base domain of the cluster. All DNS records will be sub-domains of this base and will also include the cluster name.
## This must bee the same as in terraform.tfvars
baseDomain: example.local
metadata:
  ## The name for the cluster
  name: okd
###### dns should be : *.okd.example.local

compute:
- name: worker
  replicas: 0

controlPlane:
  name: master
  replicas: 3
  
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
# To configure capabilites : https://docs.openshift.com/container-platform/4.16/installing/overview/cluster-capabilities.html
capabilities:
  baselineCapabilitySet: None # lightweight
  additionalEnabledCapabilities: 
  - CSISnapshot
  - Console
  - Storage
  - NodeTuning
  - ImageRegistry
  - marketplace
  - OperatorLifecycleManager
  
#Console, Insights, Storage, CSISnapshot, NodeTuning, ImageRegistry, Build, CloudCredential, and DeploymentConfig

## The pull secret that provides components in the cluster access to images for OpenShift components.
# a fake value to satisfy the installer. Images for okd need no subscription
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
## The default SSH key that will be programmed for `core` user.
sshKey: 'ssh-pubkey-for-instance-access'